<script setup lang="ts">
import { FAQ } from '~/utils/faq'
import { SHOW_SPONSORS } from '~/utils/sponsors'

const site = {
  url: 'https://muzak.dev',
  name: 'Muzak',
  title: 'Muzak · The type-safe web framework for Go',
  description:
    "Muzak is a type-safe web framework for Go, built on net/http and Go 1.27 with no third-party dependencies. A handler's input type is the request and its return type is the response, both checked when you compile. Install with go get muzak.dev/framework.",
}

// ── Classic SEO: title, description, Open Graph, Twitter, canonical ──
// The Open Graph / Twitter image is generated by nuxt-og-image (below), so it
// is not set here.
useSeoMeta({
  title: site.title,
  description: site.description,
  keywords:
    'Muzak, Go web framework, type-safe Go API, Go generics router, Go OpenAPI generation, Go request validation, Go dependency injection, net/http framework, Go 1.27',
  author: 'The Muzak project',
  ogType: 'website',
  ogSiteName: site.name,
  ogTitle: site.title,
  ogDescription: site.description,
  ogUrl: site.url,
  ogLocale: 'en_US',
  twitterCard: 'summary_large_image',
  twitterTitle: site.title,
  twitterDescription: site.description,
  robots: 'index, follow, max-image-preview:large, max-snippet:-1',
  themeColor: '#0E0C0A',
})

useHead({
  htmlAttrs: { lang: 'en' },
  link: [{ rel: 'canonical', href: site.url }],
})

// The social banner, generated from the Muzak OG template.
// The card already carries the "Muzak" wordmark at the top and the tagline
// along the bottom, so passing the full page title repeated both of them and
// the card said the same thing three times. The hero's own headline is what is
// actually distinctive about this page.
defineOgImageComponent('Muzak', {
  title: 'The signature is the contract.',
  description: site.description,
})

// ── GEO / structured data: give engines clean, citable facts ──
const ldSoftware = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Muzak',
  applicationCategory: 'DeveloperApplication',
  applicationSubCategory: 'Web Framework',
  operatingSystem: 'Linux, macOS, Windows',
  description: site.description,
  url: site.url,
  softwareVersion: '0.2.0',
  programmingLanguage: 'Go',
  runtimePlatform: 'Go 1.27',
  downloadUrl: 'https://github.com/muzak-dev/framework',
  license: 'https://opensource.org/license/mit',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  // No aggregateRating here on purpose: there are no ratings to aggregate, and
  // review markup for reviews that do not exist is the kind of structured data
  // search engines penalise rather than reward.
  author: {
    '@type': 'Organization',
    name: 'The Muzak project',
    url: site.url,
  },
}

const ldFaq = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ.map((item) => ({
    '@type': 'Question',
    name: item.q,
    acceptedAnswer: { '@type': 'Answer', text: item.a },
  })),
}

const ldBreadcrumb = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: site.url },
    { '@type': 'ListItem', position: 2, name: 'Install', item: `${site.url}#install` },
    { '@type': 'ListItem', position: 3, name: 'Contract', item: `${site.url}#contract` },
    { '@type': 'ListItem', position: 4, name: 'Benchmarks', item: `${site.url}#bench` },
    { '@type': 'ListItem', position: 5, name: 'FAQ', item: `${site.url}#faq` },
  ],
}

const ldWebsite = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: site.name,
  url: site.url,
  description: site.description,
}

useHead({
  script: [
    { type: 'application/ld+json', innerHTML: JSON.stringify(ldSoftware) },
    { type: 'application/ld+json', innerHTML: JSON.stringify(ldFaq) },
    { type: 'application/ld+json', innerHTML: JSON.stringify(ldBreadcrumb) },
    { type: 'application/ld+json', innerHTML: JSON.stringify(ldWebsite) },
  ],
})
</script>

<template>
  <main id="top" class="relative z-10">
    <HeroSection />
    <InstallSection />
    <ContractSection />
    <BenchmarksSection />
    <FaqSection />
    <!-- Off for the first release; see SHOW_SPONSORS in utils/sponsors.ts. -->
    <SponsorsSection v-if="SHOW_SPONSORS" />
    <CtaSection />
  </main>
</template>
